#ifndef DRIVER_COMMANDS_H
#define DRIVER_COMMANDS_H

#define DEV_NAME "throttling"
#define IOCTL_MAGIC 'M'
#define IOCTL_ENABLE_THROTTLING _IO(IOCTL_MAGIC, 1)
#define IOCTL_DISABLE_THROTTLING _IO(IOCTL_MAGIC, 2)
#define IOCTL_REGISTER_SN _IOW(IOCTL_MAGIC, 3, int)
#define IOCTL_UNREGISTER_SN _IOW(IOCTL_MAGIC, 4, int)
#define IOCTL_REGISTER_EUID _IOW(IOCTL_MAGIC, 5, char*)
#define IOCTL_UNREGISTER_EUID _IOW(IOCTL_MAGIC, 6, char*)
#define IOCTL_REGISTER_PN _IOW(IOCTL_MAGIC, 7, char*)
#define IOCTL_UNREGISTER_PN _IOW(IOCTL_MAGIC, 8, char*)
#define IOCTL_SET_MAX_RATE _IOW(IOCTL_MAGIC, 9, int) 

#endif